fix: 3box/v03id derivation
ceramicstudio/js-3id-did-provider pull request #112
Opened 2021-02-01 19:05 UTC by zachferland

Changes root key derivation path (to what exist in 3box/3id-connect, would have been root store path if migration had occurred in 3box, but ceramic migration path was favored over completing that migration )

One issue remains, did resolver when resolving legacy dids (mocked in test here for example) throws 'not a valid 3id' when using an uncompressed signing key. Results in failed test here, while same key compressed passes.

2021-02-02 09:44 UTC, oed requested changes
One change needed.

2021-02-02 09:44 UTC, oed commented on src/keyring.ts
> +const LEGACY_BASE_PATH = "m/7696500'/0'/0'"
haha, I bet this is the one that says `muport`. Anyway, this will make things faster 👍

2021-02-02 09:44 UTC, oed commented on src/keyring.ts
> +  if (v03ID) hdNode = seedNode.derivePath(LEGACY_BASE_PATH)
`derivePath` is a very expensive operation! Please make it happen only once if it's a `v03ID`.

2021-02-02 09:49 UTC, oed commented
Should be straight forward to add decompression to `3id-did-resolver` by removing the *y* variable I think. 

While you are at it, looks like this line needs to use the proper `DocOpts`: https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/3id-did-resolver/src/index.ts#L92

2021-02-07 09:55 UTC, oed approved these changes
Lgtm once tests pass

2021-02-07 16:00 UTC, zachferland commented
hmm yeah they pass locally now with fix, not sure what happened to dependency here yet


Sent from my iPhone

> On Feb 7, 2021, at 04:55, Joel Thorstensson <notifications@github.com> wrote:
> 
> ﻿
> @oed approved this pull request.
> 
> Lgtm once tests pass
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-02-08 19:58 UTC, merged